#!/bin/bash
echo Welcome, This is an autometed script to turn a typical(normal) linux Mint installation into a user-friendly one with KU theme
echo We want to provide a malwere free fast computing experience to next generation and reviving old machines
